import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans, Dancing_Script } from "next/font/google";
import "./globals.css";
import { InvitationLoader } from "@/app/components/InvitationLoader";

const notoSans = Noto_Sans({variable:'--font-sans'});

const dancingScript = Dancing_Script({
  variable: '--font-handwriting',
  subsets: ['latin'],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSans.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dancingScript.variable} antialiased`}
      >
        <InvitationLoader />
        {children}
      </body>
    </html>
  );
}
